// import localFont from "next/font/local"
import Header from "./_components/Header"
import "./../sass/main.scss"

// const alta = localFont({
// 	src: "./fonts/alta-regular.otf",
// 	variable: "--font-alta",
// 	weight: "100 900",
// })
// const raleway = localFont({
// 	src: "./fonts/Raleway.ttf",
// 	variable: "--font-raleway",
// 	weight: "100 900",
// })

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
			</body>
		</html>
	)
}
